name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Make Artifact
        uses: actions/upload-artifact@v2
        with:
            name: app-release-signed
            path: ${{steps.sign_app.outputs.signedFile}}

      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
            mention-authors: false
            mention-new-contributors: false
            include-compare: false
            semver: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: ${{ steps.changelog.outputs.changelog }} &#x20;
        env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{steps.sign_app.outputs.signedFile}}
            asset_name: app-release-signed-${{ steps.var.outputs.tag }}.apk
            asset_content_type: application/zip
